dist: xenial
language: python

# some configuration for llvm (numba)
env:
  global:
    PIP_PREFER_BINARY=true # https://github.com/numba/llvmlite/issues/471

# Existing Python versions
python:
  - "3.5"
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py -q install
  - pip install -r requirements_ci.txt

# run tests
script:
  # first disable Numba so the Python coverage reporting is correct
  - export NUMBA_DISABLE_JIT=1
  - python -m pytest --cov=PyNomaly

# report results
after_success:
  - coveralls