language: python
# Existing Python versions
python:
  - 3.4
  - 3.5
  - 3.6
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py -q install
  - pip install coveralls
  - pip install pandas
  - pip install --upgrade pytest
  - pip install --upgrade pytest-cov
  - pip install scikit-learn
  - pip install scipy
# command to run tests
script:
  - python -m pytest --cov=PyNomaly
after_success:
  - coveralls